/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.awt.Color;
import java.awt.PopupMenu;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import koneksi_db.koneksi;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Lenovo
 */
public class dashboard2 extends javax.swing.JFrame {
    private final Connection conn = new koneksi().connect();
    DefaultTableModel tabmode;
    
    JasperReport JasperReport;
    JasperDesign JasperDesign;
    JasperPrint JasperPrint;
    Map<String, Object> param = new HashMap<>();
    /**
     * Creates new form dashboard2
     */
    public dashboard2() {
        initComponents();
        
        activePegawai.setVisible(false);
        activeBuku.setVisible(false);
        activePengunjung.setVisible(false);
        activePeminjaman.setVisible(false);
        activePengembalian.setVisible(false);
        activeLaporan.setVisible(false);
        activeDenda.setVisible(false);
        
        
        
        
//        laporantext2.setVisible(false);
//        laporantext3.setVisible(false);
//        laporantext4.setVisible(false);
//        laporantext5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pengunjungtext = new javax.swing.JLabel();
        activePengunjung = new javax.swing.JLabel();
        bukutext = new javax.swing.JLabel();
        activeBuku = new javax.swing.JLabel();
        pegawaitext = new javax.swing.JLabel();
        activePegawai = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        peminjamantext = new javax.swing.JLabel();
        activePeminjaman = new javax.swing.JLabel();
        pengembaliantext = new javax.swing.JLabel();
        activePengembalian = new javax.swing.JLabel();
        dendatext = new javax.swing.JLabel();
        activeDenda = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        activeLaporan = new javax.swing.JLabel();
        maincontainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(64, 142, 249));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo-07-07.png"))); // NOI18N
        jLabel1.setText("PERPUSTAKAAN SINAR BANGSA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(756, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(23, 48, 82));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setFocusTraversalPolicyProvider(true);
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 620));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MASTER");

        pengunjungtext.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        pengunjungtext.setForeground(new java.awt.Color(255, 255, 255));
        pengunjungtext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-04.png"))); // NOI18N
        pengunjungtext.setText("Data Pengunjung");
        pengunjungtext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pengunjungtext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pengunjungtextMouseClicked(evt);
            }
        });

        activePengunjung.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        activePengunjung.setForeground(new java.awt.Color(64, 142, 249));
        activePengunjung.setText("|");

        bukutext.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        bukutext.setForeground(new java.awt.Color(255, 255, 255));
        bukutext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-01.png"))); // NOI18N
        bukutext.setText("Data Buku");
        bukutext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bukutext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bukutextMouseClicked(evt);
            }
        });

        activeBuku.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        activeBuku.setForeground(new java.awt.Color(64, 142, 249));
        activeBuku.setText("|");

        pegawaitext.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        pegawaitext.setForeground(new java.awt.Color(255, 255, 255));
        pegawaitext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-06.png"))); // NOI18N
        pegawaitext.setText("Data Pegawai");
        pegawaitext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pegawaitext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pegawaitextMouseClicked(evt);
            }
        });

        activePegawai.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        activePegawai.setForeground(new java.awt.Color(64, 142, 249));
        activePegawai.setText("|");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Transaksi");

        peminjamantext.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        peminjamantext.setForeground(new java.awt.Color(255, 255, 255));
        peminjamantext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-03.png"))); // NOI18N
        peminjamantext.setText("Peminjaman");
        peminjamantext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peminjamantext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peminjamantextMouseClicked(evt);
            }
        });

        activePeminjaman.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        activePeminjaman.setForeground(new java.awt.Color(64, 142, 249));
        activePeminjaman.setText("|");

        pengembaliantext.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        pengembaliantext.setForeground(new java.awt.Color(255, 255, 255));
        pengembaliantext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-05.png"))); // NOI18N
        pengembaliantext.setText("Pengembalian");
        pengembaliantext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pengembaliantext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pengembaliantextMouseClicked(evt);
            }
        });

        activePengembalian.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        activePengembalian.setForeground(new java.awt.Color(64, 142, 249));
        activePengembalian.setText("|");

        dendatext.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        dendatext.setForeground(new java.awt.Color(255, 255, 255));
        dendatext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-05.png"))); // NOI18N
        dendatext.setText("Denda");
        dendatext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dendatext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dendatextMouseClicked(evt);
            }
        });

        activeDenda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        activeDenda.setForeground(new java.awt.Color(64, 142, 249));
        activeDenda.setText("|");

        jLabel23.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Report");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("LOG OUT");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel4AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-02.png"))); // NOI18N
        jLabel25.setText("Laporan");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });

        activeLaporan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        activeLaporan.setForeground(new java.awt.Color(64, 142, 249));
        activeLaporan.setText("|");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(activePengunjung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pengunjungtext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(76, 76, 76))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(activeBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bukutext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(115, 115, 115))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(activePegawai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pegawaitext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(95, 95, 95))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(activePeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(peminjamantext)
                                .addGap(104, 104, 104))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(activePengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pengembaliantext)
                                .addGap(92, 92, 92))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(activeDenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dendatext)
                                .addGap(137, 137, 137))
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(activeLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25)
                                .addGap(127, 127, 127))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel23))
                        .addGap(41, 41, 41))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(activePengunjung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pengunjungtext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(activeBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bukutext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(activePegawai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pegawaitext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(activePeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(peminjamantext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(activePengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pengembaliantext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activeDenda)
                    .addComponent(dendatext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(activeLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(146, 146, 146)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(119, 119, 119))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        maincontainer.setBackground(new java.awt.Color(255, 255, 255));
        maincontainer.setLayout(new java.awt.BorderLayout());
        jPanel1.add(maincontainer, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bukutextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bukutextMouseClicked
        // TODO add your handling code here:
        activePegawai.setVisible(false);
        activeBuku.setVisible(true);
        activePengunjung.setVisible(false);
        activePeminjaman.setVisible(false);
        activePengembalian.setVisible(false);
        activeLaporan.setVisible(false);
        activeDenda.setVisible(false);
        
//        laporantext2.setVisible(false);
//        laporantext3.setVisible(false);
//        laporantext4.setVisible(false);
//        laporantext5.setVisible(false);
        
        maincontainer.removeAll();
        maincontainer.add(new formBuku());
       maincontainer.repaint();
        maincontainer.revalidate();
    }//GEN-LAST:event_bukutextMouseClicked

    private void jLabel4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel4AncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel4AncestorAdded

    private void pengembaliantextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengembaliantextMouseClicked
        // TODO add your handling code here:
        activePegawai.setVisible(false);
        activeBuku.setVisible(false);
        activePengunjung.setVisible(false);
        activePeminjaman.setVisible(false);
        activePengembalian.setVisible(true);
        activeLaporan.setVisible(false);
        activeDenda.setVisible(false);
        
//        laporantext2.setVisible(false);
//        laporantext3.setVisible(false);
//        laporantext4.setVisible(false);
//        laporantext5.setVisible(false);
        
        maincontainer.removeAll();
        maincontainer.add(new formpengembalian1());
        maincontainer.repaint();
        maincontainer.revalidate();
    }//GEN-LAST:event_pengembaliantextMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void pegawaitextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pegawaitextMouseClicked
        // TODO add your handling code here:
        activePegawai.setVisible(true);
        activeBuku.setVisible(false);
        activePengunjung.setVisible(false);
        activePeminjaman.setVisible(false);
        activePengembalian.setVisible(false);   
        activeLaporan.setVisible(false);
        activeDenda.setVisible(false);
        
//        laporantext2.setVisible(false);
//        laporantext3.setVisible(false);
//        laporantext4.setVisible(false);
//        laporantext5.setVisible(false);
//        mainpanel.removeAll();
////        mainpanel.add(new frompustakawan());
//        mainpanel.repaint();
//        mainpanel.revalidate();
//            new frompustakawan().setVisible(true);

//        frompustakawan obat = new frompustakawan();
//        mainpanel.add(obat);
//        obat.setVisible(true);

        maincontainer.removeAll();
        maincontainer.add(new formpustakawan());
        maincontainer.repaint();
        maincontainer.revalidate();
    }//GEN-LAST:event_pegawaitextMouseClicked

    private void pengunjungtextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengunjungtextMouseClicked
        // TODO add your handling code here:
        activePegawai.setVisible(false);
        activeBuku.setVisible(false);
        activePengunjung.setVisible(true);
        activePeminjaman.setVisible(false);
        activePengembalian.setVisible(false);
        activeLaporan.setVisible(false);
        activeDenda.setVisible(false);
        
//        laporantext2.setVisible(false);
//        laporantext3.setVisible(false);
//        laporantext4.setVisible(false);
//        laporantext5.setVisible(false);
        
        
        maincontainer.removeAll();
        maincontainer.add(new datapengunjung());
        maincontainer.repaint();
        maincontainer.revalidate();
    }//GEN-LAST:event_pengunjungtextMouseClicked

    private void peminjamantextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peminjamantextMouseClicked
        // TODO add your handling code here:
        activePegawai.setVisible(false);
        activeBuku.setVisible(false);
        activePengunjung.setVisible(false);
        activePeminjaman.setVisible(true);
        activePengembalian.setVisible(false);
        activeLaporan.setVisible(false);
        activeDenda.setVisible(false);
        
//        laporantext2.setVisible(false);
//        laporantext3.setVisible(false);
//        laporantext4.setVisible(false);
//        laporantext5.setVisible(false);
        
        
        maincontainer.removeAll();
        maincontainer.add(new formpeminjaman());
        maincontainer.repaint();
        maincontainer.revalidate();
    }//GEN-LAST:event_peminjamantextMouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
        activePegawai.setVisible(false);
        activeBuku.setVisible(false);
        activePengunjung.setVisible(false);
        activePeminjaman.setVisible(false);
        activePengembalian.setVisible(false);
        activeLaporan.setVisible(true);
        activeDenda.setVisible(false);
        
        
        maincontainer.removeAll();
        maincontainer.add(new formlaporan());
       maincontainer.repaint();
        maincontainer.revalidate();
//        laporantext2.setVisible(true);
//        laporantext3.setVisible(true);
//        laporantext4.setVisible(true);
//        laporantext5.setVisible(true);
    }//GEN-LAST:event_jLabel25MouseClicked

    private void dendatextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dendatextMouseClicked
        // TODO add your handling code here:
        activePegawai.setVisible(false);
        activeBuku.setVisible(false);
        activePengunjung.setVisible(false);
        activePeminjaman.setVisible(false);
        activePengembalian.setVisible(false);
        activeLaporan.setVisible(false);
        activeDenda.setVisible(true);
        
//        laporantext2.setVisible(false);
//        laporantext3.setVisible(false);
//        laporantext4.setVisible(false);
//        laporantext5.setVisible(false);
        
        maincontainer.removeAll();
        maincontainer.add(new formdenda());
        maincontainer.repaint();
        maincontainer.revalidate();
    }//GEN-LAST:event_dendatextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activeBuku;
    private javax.swing.JLabel activeDenda;
    private javax.swing.JLabel activeLaporan;
    private javax.swing.JLabel activePegawai;
    private javax.swing.JLabel activePeminjaman;
    private javax.swing.JLabel activePengembalian;
    private javax.swing.JLabel activePengunjung;
    private javax.swing.JLabel bukutext;
    private javax.swing.JLabel dendatext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel maincontainer;
    private javax.swing.JLabel pegawaitext;
    private javax.swing.JLabel peminjamantext;
    private javax.swing.JLabel pengembaliantext;
    private javax.swing.JLabel pengunjungtext;
    // End of variables declaration//GEN-END:variables
}
